### ISSUE TITLE
Badge border is pixelated

### ISSUE THREAD

**Issue by mdabrarniyazi** [marketplacer/swift-badge#8] opened 2016-09-18 06:49 UTC

**Comment by evgenyneu** [comment] 2016-09-18 07:01
Hello @mdabrarniyazi, thanks for your request. The recent version of the library has already been updated to Swift 3.0 syntax. Do you have any difficulties with it in Xcode 8?

**Comment by mdabrarniyazi** [comment] 2016-09-18 07:08
@evgenyneu Hi, Sorry I didn't notice.
Is there any way I can change the shape of badge, like square or triangle!

**Comment by evgenyneu** [comment] 2016-09-18 07:52
It is alright. Good question about the shape. No, unfortunately the badges are rectangular with rounded corners at the moment.

**Comment by mdabrarniyazi** [comment] 2016-09-18 08:27
@evgenyneu Thank you. Please provide this in future if you could.

Also when I am using it in my project, badge quality is decreasing. Border looks like broken or somewhat blurred.

**Comment by evgenyneu** [comment] 2016-09-18 10:01
Thank you for reporting this bug. Could you provide the settings you use (sizes, colours, paddings, border widths) so I can reproduce it? A screenshot would also be very helpful. Thank you.

**Comment by mdabrarniyazi** [comment] 2016-09-18 15:05
![screen shot 2016-09-18 at 8 33 34 pm](https://cloud.githubusercontent.com/assets/14070787/18616787/3904952e-7ddf-11e6-9602-cdba992ec92e.png)
@evgenyneu If you notice it looks like low quality.Check border, it's 2.  This is 160_160. I want size from 50_50 to 160*160 and border 2 to 5.

**Comment by evgenyneu** [comment] 2016-09-18 22:59
Thanks for the info, @mdabrarniyazi. I have used your parameters to make the badge and I could not reproduce your issue. The badge edge looks smooth both on iOS 10 device and emulator. There is clearly something else that I am missing. What could it be?

Please find the demo project and the screenshot and the attached.

[UsingBadgeSwift.zip](https://github.com/marketplacer/swift-badge/files/479032/UsingBadgeSwift.zip)

<img src='https://cloud.githubusercontent.com/assets/880411/18619720/31d34f1c-7e47-11e6-9ec2-72fe2b67f4d6.png' width='320'>

**Comment by evgenyneu** [comment] 2016-11-11 03:18
Hi @mdabrarniyazi, just an update. One can now specify the corner radius for the badge. You asked if the badge can be a square. Yes, now one can make it square by setting the corner radius to zero. All the best.

**Comment by evgenyneu** [comment] 2016-11-13 01:55
Closing the issue, feel free to reopen if it still exists.

**Closed as completed by evgenyneu** 2016-11-13 01:55 UTC
